# Spark defaults for Delta Lake + MinIO (S3A)
spark.sql.extensions                          io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog               org.apache.spark.sql.delta.catalog.DeltaCatalog

# S3A (MinIO) Configuration — credentials injected via entrypoint.sh from environment
spark.hadoop.fs.s3a.path.style.access         true
spark.hadoop.fs.s3a.impl                      org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled     false

# Warehouse directory
spark.sql.warehouse.dir                       s3a://gold/warehouse

#Prometheus endpoint từ Spark UI:           
spark.ui.prometheus.enabled                  true